### ISSUE TITLE
Missing/Invalid UTXO Bug

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#121]
```
plasmacli keys list
NAME:		ADDRESS:
acc1		0xec36ead9c897b609a4ffa5820e1b2b137d454343
acc2		0x5475b99e01ac3bb08b24fd754e2868dbb829bc3a
```
First Tx:
```
plasmacli spend 0xec36ead9c897b609a4ffa5820e1b2b137d454343 1000000000,0 acc1 --position "(0.0.0.2)"
```
Second Tx:
```
 plasmacli spend 0x5475b99e01ac3bb08b24fd754e2868dbb829bc3a 1000,0 acc2 --position "(0.0.0.3)" --sync
```
```
plasmacli query balance acc1
Position: (1.0.0.0) , Amount: 1000000000
Total: 1000000000
```

```
plasmacli query balance acc2
Position: (2.1.0.0) , Amount: 1000
Total: 1000
```
```
plasmacli eth query block 2
Block: 2
Header: 0x4f184d141febc0d7fae06787dd4f3cc243bbdcf388f663e9907a0e94208648d3
Txs: 2
Fee: 0
Created: 2019-03-04 01:15:39 +0000 UTC
```

log: 
```
I[4036-03-04|01:15:23.812] Executed block                               module=state height=3108 validTxs=1 invalidTxs=1
I[4036-03-04|01:15:23.822] Committed state                              module=state height=3108 txs=2 appHash=C01C9C675C7211AC631E7030EFB2A11D46A5E06A66E66A4EBB8589E5386CCF82
```

Possible explanation: Position 0.0.0.2 had already been spent. It appears that the first tx failed but was still included in the block. This is correct TM behavior but sketchy that plasma block includes this invalid tx.

**Comment by hamdiallam** [comment]
Why would this be correct TM behavior? Invalid txs shouldn't be included in a block. When trying to conduct and invalid spend, it would see that log except with txs=0 and invalidTxs=1

**Comment by colin-axner** [comment]
TM consumes gas for invalid txs and therefore includes them in a block. They don't update state however

**Comment by colin-axner** [comment]
I believe this means we need stronger checks in ante handler since it appears it failed while delivering state? If it fails in ante it should fail in the mempool and not be added to a block

**Comment by colin-axner** [comment]
In [this if statement](https://github.com/FourthState/plasma-mvp-sidechain/blob/6fe984d903a57776172641212f204f43aa34205c/handlers/anteHandler.go#L99) we need to add a check to see if the deposit input has been spent

**Comment by AdityaSripal** [comment]
If it failed in ante it should not be included in a TM block

**Comment by AdityaSripal** [comment]
@colin-axner But ur first tx should have fail at [this line](https://github.com/FourthState/plasma-mvp-sidechain/blob/6fe984d903a57776172641212f204f43aa34205c/handlers/anteHandler.go#L43), no?

**Comment by AdityaSripal** [comment]
NVM misunderstood the issue. This is fixed in my deposit PR

**Comment by hamdiallam** [comment]
This raises another problem though for double spends in the same block. The app object should hold a cache of seen inputs so that you can fail spends in the ante handler
