### ISSUE TITLE
Increase Efficiency of Unspent Queries

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#128]
## Summary
When querying a full node for all unspent utxo's corresponding to an address, it should not have to iterate through all utxo's every owned by this address.

## Problem

When we query the sidechain for utxo's corresponding to an address, we do a subspace search. This is a great optimization, but it also returns every utxo ever owned by this account. This is only useful when challenging/exiting (which most users won't do very often).

## Proposal
 
We should devise a method for retrieving only unspent utxo's given the context of the current state without iterating through spent utxos. There are several ways we could do this. 

One way would be to modify or add another store to app state which maintains unspent utxo's only. Mapping for these accounts could also be `<address><position>` for the key. This would be double storage, but overtime the amount of unspent utxo's compared to spent utxo's will continually decrease. 

Another way would be to change utxo store map to be `<address><spend bit><position>`, where <spend bit> is 1 if spent and 0 if unspent.

**Comment by hamdiallam** [comment]
Why not have the output mapping just be `<position> => Output`
