### ISSUE TITLE
Update Errors

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#152]
## Summary
 
The errors are not consistent within the codebase. We should follow golang guidelines for errors, as well as add errors.go files to each module and with the correct codespace. For example, "handlers" could be a codespace with a ErrTxDNE error type.

**Comment by colin-axner** [comment]
refactor DNE errors into one

**Comment by hamdiallam** [comment]
Also remove the braces `: { %s }` when wrapping errors. Instead it should be `fmt.Errorf("some error: %s", suberr)`
