### ISSUE TITLE
Folder/Package Renaming

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#16]
Currently the bulk of the application is under the package types. The name "types" does not accurately represent all the files it contains. I think we should split this package into 2. 1 folder/package containing files for validation and low level database changes (mapper) and the other folder/package for higher level application changes and structure definitions.

For example we could have the packages auth and db:
package auth contains:
- mapper.go
- ante.go
- utxo.go 

package db contains:
- handler.go 
- tx.go 
- keeper.go 
- errors.go

To work with the current version of the cosmos sdk we should add a errors.go file to define the codespace our errors will function in as outlined [here](https://github.com/cosmos/cosmos-sdk/issues/766). Notice that none of the files in package auth need to return an sdk.Error. 

Thoughts?

**Comment by hamdiallam** [comment]
I like the division

**Comment by colin-axner** [comment]
To avoid circular dependencies here is an outline of the updated package ordering:
There are five packages : app, auth, db, types, and utils
- **app**: app.go, app_test.go

- **auth**: mapper.go, mapper_test.go, ante.go, ante_test.go, handler_test.go (can't be put in db or it creates a circular dependency, needs to be able to construct a mapper)

- **db**:errors.go, handler.go, kepper.go, tx.go, tx_test.go

- **utils**: utils.go
 
- **types**:utxo.go, mapper.go (interface for utxo mapper)

**Comment by colin-axner** [comment]
Updated spec in #25
