### ISSUE TITLE
Bug in plasmad home directory

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#174]
## Summary of bug
 
home directory for plasmad is depending on current directory
## Expected behavior

uses default home regardless of what directory you are in (`.plasmad/`)
## Actual behavior

If I am not in `.plasmad` I get 
```
plasmad version
MustWriteFile failed: open config/plasma.toml: no such file or directory
```
If I am in `.plasmad`
```
plasmad version

```
## Versions/External Software

latest develop

**Comment by hamdiallam** [comment]
Have a fix up for this. However the version command does not currently print out any information.
