### ISSUE TITLE
Checking FeeUTXO Amount

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#18]
The last tx in a block needs to be a fee utxo as per our [FeeStructure](https://github.com/FourthState/plasma-research/blob/master/PlasmaMVP/feeStructure.md)

Currently this is being verified in ante.go by storing a temporary fee utxo that is updated with fee amounts until the txindex == feeTxIndex. 

The creation and deletion of utxo's for checking the fee amount seems over complicated and unnecessary. Instead similar to txIndex we can have feeAmount stored in our application and passed into ante handler. This can be updated in the ante handler by adding msg.Fee at the end of the file.

Then if txIndex == feeTxIndex we just need to check that feeAmount == msg.Fee.

This check will only be done if it is a DeliverTx and not CheckTx

**Comment by colin-axner** [comment]
Upon further discussion, instead of including a feeutxo within a block we have decided instead to include the feeAmount into the state hash. By ensuring that the feeAmount is included into the state hash (perhaps in endblocker) we can use the state hash to verify how much in fees should be allowed to be withdrawn through the root contract. 

We need to determine how we can ensure the fee amount for each block is included into the state hash and how we can get a merkle proof to show that it has been included.

**Comment by AdityaSripal** [comment]
This issue should be changed to the larger issue of how to handle fees in general.
