### ISSUE TITLE
Connecting sidechain via geth full node

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#22]
In order to verify deposits on the rootchain, the sidechain will need the capability to ping the rootcontract for the latest deposits to have happened. This will need to be done via a full geth node. 

I would suggest connecting the full geth node to either end blocker or begin blocker. Then any deposits that are verified to be on the root contract should be added into the utxo db with their position{0,0,0,depositNum}

**Comment by legengliu** [comment]
Not only for pinging for the latest deposits, also on the to-do list is implementing all the rootchain functions (submitBlock, challengeExit, etc.) right?

**Comment by colin-axner** [comment]
Yes, how this will exactly work is still to be determined. Since running plasmad is really running a validator node, and a validator would probably want to submit a block automatically whenever they are the proposer. And on the plasmacli side you'd want challengeExit and withdraw and deposit abilities, but we will want to determine if it is necessary they start up a full node to do this or if there is a less intensive way to add these commands

For submitBlock with plasmad, we currently leverage the server package from cosmos sdk to run tendermint, so I'm not sure how difficult it would be to integrate this ability

**Comment by vaibhavchellani** [comment]
shouldn't exits be challenged from main chain since the actual funds are being stored there ? If the challenging happens on tendermint and the consensus stops or more than 1/3 validators collude you wont be able to challenge successfully ,right ?

**Comment by colin-axner** [comment]
Yes, exits will be challenged on the main chain, not the side chain. [here](https://github.com/FourthState/plasma-mvp-rootchain/blob/b000573b67dd4e071e6a7259da7ec8f51abb4715/contracts/rootchain/RootChain.sol#L251) is the actual challenge function on the rootchain. But the user interface to execute a challenge transaction will probably end up being in the same interface as interacting on the sidechain. A challenge tx is a ethereum tx not a sidechain tx.
