### ISSUE TITLE
Finalized Exits

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#24]
We will need a some mechanism for taking into account utxo's that have been exited via the rootchain. This can probably be done with a finalizedExits mapping similar to the rootchain. This should be implemented where ever the geth full node is, and in the ante handler to check that the position being referenced has not been exited.

**Comment by AdityaSripal** [comment]
Sidechain state should be updated to delete UTXO as soon as it detects a startExit.

Invariant:
Once UTXO has started exit, it will either succeed or the UTXO is invalid.

**Comment by liwei00wade** [comment]
Sidechain state should be updated to delete UTXO as soon as it detects a startExit.


how to delete  UTXO  ?

**Comment by AdityaSripal** [comment]
Hello,

Again this is subject to change as we continue to iterate on the design. The sdk provides a BeginBlocker and EndBlocker function that can execute at each block.

We may use this to poll the rootchain smart contract for any startExits and delete the corresponding UTXO

**Comment by colin-axner** [comment]
Discussion in #36 resolves this issue. See the research repository for a design spec of Anchor (name for our version of peggy).
