### ISSUE TITLE
Deprecate decodePosition and nil utxo checks

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#34]
The function `decodePosition()` can be deprecated since it should never be used. We only encode the position to use it as a key for the mapping from position to utxo. 

Also, I think any check for `utxo == nil` that occurs after the ante handler has executed may also be deleted. One check is sufficient in the ante handler. The occurrence of this in keeper.go, `SpendUTXO()` may be deleted and in mapper.go in `DeleteUTXO()`

**Comment by AdityaSripal** [comment]
Also should delete Get and String methods from Msg type

**Comment by colin-axner** [comment]
Also change the string returned in Type() to "spend" instead of "txs"
