### ISSUE TITLE
Update BaseTx struct/Update to sdk v0.18.0

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#37]
BaseTx struct needs to be updated by removing StdSignature and replacing it with either:

`type BaseSignature struct { 
crypto.PubKey
crypto.Signature
}`

I also think we could just use crypto.Signature in replacement of StdSignature since, to the best of my knowledge, we never make use of the PubKey in the StdSignature struct. 

We can make this adjustment since sdk.Tx interface now only requires the GetMsg() function. This will allow us to change the TxDecoder to support RLP decoding. RLP encoding will also be added to the client package, so all txBytes included in a tendermint block are RLP encoded. 

If there are any other changes that need to be made with updating from 0.17.2 to 0.18.0, they should be noted on this issue.

**Comment by AdityaSripal** [comment]
Closed in #38
