### ISSUE TITLE
Edgecase Squared: Cross-plasmachain Replay Attack

### ISSUE THREAD

**Issue by AdityaSripal** [FourthState/plasma-mvp-sidechain#39]
Attack explained in plasma-mvp-rootchain issue.

Should change signature to include Chain-ID. Chain-ID should be rootchain smart-contract address.

**Comment by colin-axner** [comment]
Since our confirmation hash references the current root hash, this attack would need an identical history to be performed. In such a situation, the attacking chain can be considered a fork.
