### ISSUE TITLE
Implement export.go

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#40]
Currently one can manually import and export encrypted JSON key files.

- Navigate to $HOME/.plasmacli/keys and copy/paste the keyfile you want to backup or export/import

Using the Import() and Export() function from the [keystore](https://godoc.org/github.com/ethereum/go-ethereum/accounts/keystore#KeyStore) we should support the capability for users to input the file location of the key they would like to import and the ability to save an export key file to a users desired location without having to navigate to /.plasmacli/keys

**Comment by hamdiallam** [comment]
How should the named keys be handled?
