### ISSUE TITLE
More tests in app_test.go

### ISSUE THREAD

**Issue by AdityaSripal** [FourthState/plasma-mvp-sidechain#46]

**Comment by AdityaSripal** [comment]
Partially addressed. Still need more

Future tests to be written:

 -   One input, two outputs

-    Two inputs (different addresses), one output

-   Two inputs (different addresses), two outputs

-   Check txIndex increments correctly by delivering multiple tx's in single block

-   Check fee handled correctly after implemented.

The above suggested tests should probably be implemented after removing confirm sigs. Too hard otherwise.

**Comment by colin-axner** [comment]
All the tests above have been added
