### ISSUE TITLE
Switch UTXOMapper keys

### ISSUE THREAD

**Issue by AdityaSripal** [FourthState/plasma-mvp-sidechain#47]
Currently, the key is an encoded position.

We should switch this to:

<owner_address> + <encoded_position>

This will allow us to iterate through all UTXO's owned by an address using KVStorePrefixIterator.
Useful for client UX.

**Comment by legengliu** [comment]
Will start to look into this.

**Comment by AdityaSripal** [comment]
Closed in #51
