### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by AdityaSripal** [FourthState/plasma-mvp-sidechain#64]
Error messages should be more descriptive and also include the value that caused the error.

For example, if the UTXO does not exist for a transaction, error message should print out the position that tried to be spent.

**Comment by colin-axner** [comment]
When spending a deposit if presumed finality has not passed, an error message of "deposit not final" should be returned instead of "deposit does not exist"

**Comment by AdityaSripal** [comment]
Already done on my PR lol

**Comment by colin-axner** [comment]
When trying to spend a tx signing with the wrong key I get this error:
```
{"codespace":"handlers","code":1,"message":"input, [(0.0.0.0) Tu\ufffd\ufffd\u0001\ufffd;\ufffd\ufffd$\ufffduN(h۸)\ufffd:], does not exist by owner %!!(MISSING)x(MISSING)"}
```

Should replicate this error msg later, and adjust where it is being returned to be more clear

**Comment by AdityaSripal** [comment]
Strange, why would it break on `0.0.0.0` not existing (Im assuming that this is second input, and u mis-signed on first input)? Looks like it's just a bad error msg overall and we need an "incorrect signature" error msg to be returned

**Comment by colin-axner** [comment]
I think what might have occurred is since I signed with the wrong key, the utxo returned a nil position because it didn't exist in the mapping, causing the error message above
