### ISSUE TITLE
Change Hash Function

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#8]
We will need to figure out how to adjust the hash function used when forming a block. Currently tendermint uses RIPEMD160 when hashing the transaction bytes. This will need to be changed to Keccak256 to work with the root contract. 

The use of RIPEMD160 can be seen here:
https://github.com/tendermint/tendermint/blob/master/types/tx.go#L19

**Comment by AdityaSripal** [comment]
ripemd160 is a function in solidity. We can just use that instead of keccak.

Thus, this should be an issue moved to the rootchain
